travis:
  secure:
    BINSTAR_TOKEN: ilL4JAcoqoNBkVLofLi8b6d5L5aHvT081CSjx327kRnQumkKVgmjahnt+KZ2XzXDXYrareb4WDSUOdTLb2CkZvLTt9Q0o6c1sWyL2ojCTov7KBteETjKkxl7eSmeWZyHo2zfRVrZ/wbw57bHMwAaFNNWwLTF5IJFsP5Yh5fKl6j0ppBvvd7mHdYIyGga0pp1vDUXYBrKbKWE+qGoMk51frZtuXuwPV8SVOr4X920nM39hsn1EqagqaVWiwWDtujY3mT6mh8PR7qgQwYNO1G9Vmm6wH9VD7Nk1WvrRV06AwpqP9FRKP+XOqu4olflyj68E+d37KYtoLq+icTj1IzbjrdthaMe+0Yl9BaUgdBbmMTprH3HeMh8OyKL2bgNj7jzt0gs5DFH11d903FWKkjMe6ftcbyaAhCZ3jjVoq7eCZtIzt/aP+LfnLOzRBT4NOJVkpv4QywxShuS2iHlQmXRFkRzqev150iEsqAqEeFzikBWESaqQHclRxWLlUfzkwmnnWJFd90M2Ew1R76ewHF3+NLIKcAZPnLAKfwwNyz2DVsigORVuVDdZvglpQPnpFSmZ4K9470tlcpk+mBdIqShYe0/UuDhO48yAGTQliUmmq0mtasnV6b5xXVSqU9C1mjHY/vTESFObzBnkFN74k84YsDL+zbtzeg6GijMGo/kmeY=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
